template_path: nextflow-ecs-security-group.yaml
stack_name: nextflow-ecs-security-group
dependencies:
  - prod/nextflow-vpc.yaml

parameters:
  VpcId: !stack_output_external nextflow-vpc::VPCId
  SecurityGroupCidrIp: !stack_output_external nextflow-vpc::VpcCidr

stack_tags:
  {{stack_group_config.default_stack_tags}}
