template_path: nextflow-tower-secret.yaml
stack_name: nextflow-tower-secret
dependencies:
  - prod/workflows-kms-key.yaml

parameters:
  KmsKeyAlias: !stack_output_external workflows-infra-kms-key::Alias

stack_tags:
  {{stack_group_config.default_stack_tags}}
