template_path: nextflow-ecs-task-definition.j2
stack_name: nextflow-ecs-task-definition
dependencies:
  - infra-prod/nextflow-aurora-mysql.yaml
  - infra-prod/nextflow-efs-file-system.yaml

parameters:
  TowerSmtpHost: 'email-smtp.us-east-1.amazonaws.com'
  TowerSmtpPort: '587'
  TowerSmtpUser: !ssm 'smtp-username'
  TowerSmtpPassword: !ssm 'smtp-password'
  TowerContactEmail: nextflow-admins@sagebase.org
  TowerServerUrl: https://tower.sagebionetworks.org
  TowerJwtSecret: !aws_secrets_manager nextflow-tower-secret/jwt::SecretString::secret
  TowerCryptoSecretkey: !aws_secrets_manager nextflow-tower-secret/crypto::SecretString::secret
  TowerLicense: !aws_secrets_manager nextflow/license::SecretString::license_key
  TowerDbUrl: !stack_output_external nextflow-aurora-mysql::DBUrl
  TowerDbUser: !aws_secrets_manager nextflow-aurora-mysql-NextflowTowerDatabaseUserSecret::SecretString::username
  TowerDbPassword: !aws_secrets_manager nextflow-aurora-mysql-NextflowTowerDatabaseUserSecret::SecretString::password
  TowerGoogleClientId: !aws_secrets_manager nextflow/google_oauth_app::SecretString::client
  TowerGoogleSecret: !aws_secrets_manager nextflow/google_oauth_app::SecretString::secret
  RedisContainerImage: 'redis:5.0.8'
  CronContainerImage: '195996028523.dkr.ecr.eu-west-1.amazonaws.com/nf-tower-enterprise/backend:{{stack_group_config.tower_version}}'
  FrontendContainerImage: '195996028523.dkr.ecr.eu-west-1.amazonaws.com/nf-tower-enterprise/frontend:{{stack_group_config.tower_version}}'
  BackendContainerImage: '195996028523.dkr.ecr.eu-west-1.amazonaws.com/nf-tower-enterprise/backend:{{stack_group_config.tower_version}}'
  EfsFileSystemId: !stack_output_external nextflow-efs-file-system::FileSystemId
  EfsVolumeMountPath: '/efs'
  TowerUserWorkspace: 'false'
  TowerRootUsers:
    - bruno.grande@sagebase.org
    - thomas.yu@sagebase.org
  TowerConfigFileName: 'tower.yaml'

stack_tags:
  {{stack_group_config.default_stack_tags}}

sceptre_user_data:
  environment: !file src/tower/resources/environment.yaml
