project_code: aws-workflows-nextflow-infra
profile: {{ var.profile | default() }}
region: {{ var.region | default("us-east-1") }}
aws_infra_templates_root_url: https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra
admincentral_cf_bucket: bootstrap-awss3cloudformationbucket-19qromfd235z9
tower_version: v23.1.4
default_stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
  CostCenter: NO PROGRAM / 000000
notifications_email: {{ var.notifications_email | default("nextflow-admins@sagebase.org") }}
budgets:
  compute: {{ var.compute_budget | default("1000") }}
  storage: {{ var.storage_budget | default("500") }}
  security: {{ var.security_budget | default("100") }}
  other: {{ var.other_budget | default("100") }}
services:
  compute:
    - Amazon Elastic Compute Cloud - Compute
  storage:
    - Amazon Simple Storage Service
    - Amazon Elastic Block Store
  security:
    - Amazon GuardDuty
    - AWS Config
  other:
    - Amazon API Gateway
    - Amazon DynamoDB
    - Amazon Elastic Container Service
    - Amazon Elastic File System
    - Amazon Elastic Load Balancing
    - Amazon Relational Database Service
    - Amazon Route 53
    - Amazon Simple Notification Service
    - Amazon Simple Queue Service
    - Amazon Virtual Private Cloud
    - AmazonCloudWatch
    - AWS Backup
    - AWS CloudShell
    - AWS CloudTrail
    - AWS DataSync
    - AWS Glue
    - AWS Key Management Service
    - AWS Lambda
    - AWS Secrets Manager
    - AWS Service Catalog
    - AWS Systems Manager
