TOWER_CONTACT_EMAIL: "!Ref 'TowerContactEmail'"
TOWER_SMTP_HOST: "!Ref 'TowerSmtpHost'"
TOWER_SMTP_PORT: "!Ref 'TowerSmtpPort'"
TOWER_SMTP_USER: "!Ref 'TowerSmtpUser'"
TOWER_SMTP_PASSWORD: "!Ref 'TowerSmtpPassword'"
TOWER_DB_URL: "!Ref 'TowerDbUrl'"
TOWER_DB_DRIVER: "com.mysql.cj.jdbc.Driver"
TOWER_DB_DIALECT: "io.seqera.util.MySQL55DialectCollateBin"
TOWER_DB_USER: "!Ref 'TowerDbUser'"
TOWER_DB_PASSWORD: "!Ref 'TowerDbPassword'"
TOWER_SERVER_URL: "!Ref 'TowerServerUrl'"
TOWER_JWT_SECRET: "!Ref 'TowerJwtSecret'"
TOWER_CRYPTO_SECRETKEY: "!Ref 'TowerCryptoSecretkey'"
TOWER_LICENSE: "!Ref 'TowerLicense'"
FLYWAY_LOCATIONS: "classpath:db-schema/mysql"
TOWER_GOOGLE_CLIENT: "!Ref TowerGoogleClientId"
TOWER_GOOGLE_SECRET: "!Ref TowerGoogleSecret"
TOWER_OIDC_CLIENT: "!If [ HasTowerOidcClient, !Ref TowerOidcClientId, !Ref AWS::NoValue]"
TOWER_OIDC_SECRET: "!If [ HasTowerOidcClient, !Ref TowerOidcSecret, !Ref AWS::NoValue]"
TOWER_OIDC_ISSUER: "!If [ HasTowerOidcClient, !Ref TowerOidcIssuer, !Ref AWS::NoValue]"
TOWER_OIDC_TOKEN_IMPORT: "!If [ HasTowerOidcClient, !Ref TowerOidcTokenImport, !Ref AWS::NoValue]"
TOWER_ROOT_USERS: "!If [ HasTowerRootUsers, !Join [',', !Ref TowerRootUsers], !Ref AWS::NoValue]"
TOWER_CONFIG_FILE: "!Sub '${EfsVolumeMountPath}/${TowerConfigFileName}'"
