name: aws-deploy

on: push

jobs:
  pre-commit:
    name: Run pre-commit hooks against all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.2

  sceptre-deploy:
    name: Deploy CloudFormation templates using sceptre
    runs-on: ubuntu-latest
    needs: pre-commit
    if: github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NEXTFLOW_PROD_CI_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.NEXTFLOW_PROD_CI_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::728882028485:role/workflows-nextflow-ci-service-account-ServiceRole-CTLXKJIOCRO4
          role-duration-seconds: 1200
      - name: Deploy 'prod' templates
        uses: Rurquhart/sceptre-action@v1.0
        with:
          sceptre_version: 2.4.0
          sceptre_subcommand: launch --yes prod
