template_path: tower-project.yaml
stack_name: agora-project

stack_tags:
  Department: ADTR
  Project: Agora
  OwnerEmail: brad.macdonald@sagebase.org
  CostCenter: Agora / 112300

parameters:
  S3ReadWriteAccessArns:
    - "{{stack_group_config.tower_viewer_arn_prefix}}/brad.macdonald@sagebase.org"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/thomas.yu@sagebase.org"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/jessica.britton@sagebase.org"
  AccountAdminArns:
    - "{{stack_group_config.sso_admin_role.arn}}"
    - !stack_output_external workflows-nextflow-ci-service-account::ServiceRoleArn
  TemplateRootUrl: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com"
  TowerForgePolicyArn: !stack_output_external nextflow-forge-iam-policy::NextFlowForgePolicyArn
  TowerLaunchPolicyArn: !stack_output_external nextflow-launch-iam-policy::NextFlowLaunchPolicyArn

dependencies:
  - common/nextflow-forge-iam-policy.yaml
  - common/nextflow-launch-iam-policy.yaml
