template:
  path: tower-project.j2
stack_name: wei-an-chen-project
dependencies:
  - common/nextflow-forge-iam-policy.yaml
  - common/nextflow-launch-iam-policy.yaml

parameters:
  S3ReadWriteAccessArns:
    - '{{stack_group_config.tower_viewer_arn_prefix}}/william.poehlman@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/wei-an.chen@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/thomas.yu@sagebase.org'
  AllowSynapseIndexing: Enabled
  AccountAdminArns:
    - '{{stack_group_config.sso_admin_role.arn}}'
    - !stack_output_external github-oidc-nextflow-infra::ProviderRoleArn
  TemplateRootUrl: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com'
  TowerForgePolicyArn: !stack_output_external nextflow-forge-iam-policy::NextFlowForgePolicyArn
  TowerLaunchPolicyArn: !stack_output_external nextflow-launch-iam-policy::NextFlowLaunchPolicyArn

stack_tags:
  Department: NDR
  Project: amp-ad
  OwnerEmail: wei-an.chen@sagebase.org
